spring:
  application:
    name: tinecommerce-admin
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  liquibase.change-log: classpath:sql/db-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/tinecommerce
    username: tineuser
    password: password
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
    properties.hibernate.jdbc.lob.non_contextual_creation: true
server:
  port: 9000